vetenary/config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :pets
  resources :customers
  resources :pdoctors
  resources :doctors

   root 'appointments#index'

end

vetenary/app/models/pdoctor.rb
class Pdoctor < ActiveRecord::Base
 has_many :pets
end

vetenary/app/controllers/pdoctors_controller.rb
class PdoctorsController < ApplicationController
  before_action :set_pdoctor, only: [:show, :edit, :update, :destroy]

  # GET /pdoctors
  # GET /pdoctors.json
  def index
    @pdoctors = Pdoctor.all
  end

  # GET /pdoctors/1
  # GET /pdoctors/1.json
  def show
  end

  # GET /pdoctors/new
  def new
    @pdoctor = Pdoctor.new
  end

  # GET /pdoctors/1/edit
  def edit
  end

  # POST /pdoctors
  # POST /pdoctors.json
  def create
    @pdoctor = Pdoctor.new(pdoctor_params)

    respond_to do |format|
      if @pdoctor.save
        format.html { redirect_to @pdoctor, notice: 'Pdoctor was successfully created.' }
        format.json { render :show, status: :created, location: @pdoctor }
      else
        format.html { render :new }
        format.json { render json: @pdoctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pdoctors/1
  # PATCH/PUT /pdoctors/1.json
  def update
    respond_to do |format|
      if @pdoctor.update(pdoctor_params)
        format.html { redirect_to @pdoctor, notice: 'Pdoctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @pdoctor }
      else
        format.html { render :edit }
        format.json { render json: @pdoctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pdoctors/1
  # DELETE /pdoctors/1.json
  def destroy
    @pdoctor.destroy
    respond_to do |format|
      format.html { redirect_to pdoctors_url, notice: 'Pdoctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pdoctor
      @pdoctor = Pdoctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pdoctor_params
      params.require(:pdoctor).permit(:nameofpet, :type, :breed, :age, :weight, :dateofvist)
    end
end

vetenary/app/helpers/pdoctors_helper.rb
module PdoctorsHelper
end

vetenary/app/views/pdoctors/_form.html.erb
<%= form_for(@pdoctor) do |f| %>
  <% if @pdoctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pdoctor.errors.count, "error") %> prohibited this pdoctor from being saved:</h2>

      <ul>
      <% @pdoctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nameofpet %><br>
    <%= f.text_field :nameofpet %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :dateofvist %><br>
    <%= f.datetime_select :dateofvist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vetenary/app/views/pdoctors/edit.html.erb
<h1>Editing Pdoctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @pdoctor %> |
<%= link_to 'Back', pdoctors_path %>

vetenary/app/views/pdoctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pdoctors</h1>

<table>
  <thead>
    <tr>
	  <th>ID</th>
      <th>Nameofpet</th>
      <th>Breed</th>
      <th>Age</th>
      <th>Weight</th>
      <th>Dateofvist</th>
      <th colspan="3"></th>
	  <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pdoctors.each do |pdoctor| %>
      <tr>
	    <td><%= pdoctor.id %></td>
        <td><%= pdoctor.nameofpet %></td>
        <td><%= pdoctor.breed %></td>
        <td><%= pdoctor.age %></td>
        <td><%= pdoctor.weight %></td>
        <td><%= pdoctor.dateofvist %></td>
        <td><%= link_to 'Show', pdoctor %></td>
        <td><%= link_to 'Edit', edit_pdoctor_path(pdoctor) %></td>
        <td><%= link_to 'Destroy', pdoctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<td><%= link_to 'New pet', new_pet_path(:pdoctor_id => pdoctor.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pdoctor', new_pdoctor_path %>

vetenary/app/views/pdoctors/new.html.erb
<h1>New Pdoctor</h1>

<%= render 'form' %>

<%= link_to 'Back', pdoctors_path %>

vetenary/app/views/pdoctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nameofpet:</strong>
  <%= @pdoctor.nameofpet %>
</p>

<p>
  <strong>Type:</strong>
  <%= @pdoctor.type %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @pdoctor.breed %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pdoctor.age %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pdoctor.weight %>
</p>

<p>
  <strong>Dateofvist:</strong>
  <%= @pdoctor.dateofvist %>
</p>

<%= link_to 'Edit', edit_pdoctor_path(@pdoctor) %> |
<%= link_to 'Back', pdoctors_path %>